### ISSUE TITLE
Integrate with Databases

### ISSUE THREAD

**Issue by urieljuliatti** [lukelex/csvash#4]
I got an idea to implement a new feature involving databases, specially ActiveRecord in a first moment. The goal is to allow the method "modelify" use models inherited from ActiveRecord.

**Comment by lukelex** [comment]
But if we are already supporting Ruby classes should not that be enough to allow every database interface to be used alongside?

**Comment by urieljuliatti** [comment]
Sorry Lukas, maybe you got me wrong. The only thing to do is require a ruby class that implements ActiveRecord depedencies. Inside our csvash.rb we could add something like this, for example:  `require "csvash/models/active_record" if defined?(::ActiveRecord)`  and then implement ActiveRecord class as seen at `https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/models/active_record.rb`. It's just an idea ;)
